import '../constants.dart';
import '../models/payment_error.dart';

/// Validates CinetPay payment tokens.
///
/// Payment tokens are alphanumeric strings (plus hyphens and underscores)
/// between 10 and 128 characters. They are generated by the CinetPay API
/// on the backend and must not be empty or malformed.
class TokenValidator {
  TokenValidator._();

  /// Validates a payment token and returns `null` if valid.
  ///
  /// Returns a [PaymentError] describing the issue if the token is invalid.
  static PaymentError? validate(String? paymentToken) {
    if (paymentToken == null || paymentToken.isEmpty) {
      return const PaymentError(
        code: 'INVALID_TOKEN',
        message:
            'Payment token is required. Obtain one from your backend by '
            'calling the CinetPay API (POST /v1/payment).',
      );
    }

    if (paymentToken.length < CinetPayConstants.tokenMinLength) {
      return PaymentError(
        code: 'INVALID_TOKEN',
        message:
            'Payment token is too short (${paymentToken.length} chars). '
            'Minimum length is ${CinetPayConstants.tokenMinLength} characters.',
      );
    }

    if (paymentToken.length > CinetPayConstants.tokenMaxLength) {
      return PaymentError(
        code: 'INVALID_TOKEN',
        message:
            'Payment token is too long (${paymentToken.length} chars). '
            'Maximum length is ${CinetPayConstants.tokenMaxLength} characters.',
      );
    }

    if (!CinetPayConstants.tokenPattern.hasMatch(paymentToken)) {
      return const PaymentError(
        code: 'INVALID_TOKEN',
        message:
            'Payment token contains invalid characters. '
            'Expected alphanumeric characters, hyphens, and underscores only.',
      );
    }

    return null;
  }

  /// Returns `true` if the token is valid.
  static bool isValid(String? paymentToken) =>
      validate(paymentToken) == null;
}
