import 'payment_error.dart';
import 'payment_response.dart';

/// Callback signature for payment result events.
typedef PaymentCallback = void Function(PaymentResponse data);

/// Callback signature for error events.
typedef ErrorCallback = void Function(PaymentError error);

/// Callback signature for the close event.
typedef CloseCallback = void Function();

/// Configuration for the CinetPay checkout flow.
///
/// The [paymentToken] is the only required parameter. It must be obtained
/// from your backend by calling the CinetPay API (`POST /v1/payment`) using
/// one of the server-side SDKs (cinetpay-js, cinetpay-python, cinetpay-go, etc.).
///
/// All callbacks are optional. Use them to react to payment events in your app.
class CheckoutConfig {
  /// Creates a [CheckoutConfig].
  ///
  /// The [paymentToken] must be a non-empty alphanumeric string (10-128 chars)
  /// obtained from your backend.
  const CheckoutConfig({
    required this.paymentToken,
    this.onPaymentSuccess,
    this.onPaymentFailed,
    this.onPaymentPending,
    this.onClose,
    this.onError,
  });

  /// The payment token obtained from your backend.
  ///
  /// This token is generated by calling the CinetPay API `POST /v1/payment`
  /// and is used to load the checkout page at
  /// `https://secure.cinetpay.net/checkout/{paymentToken}`.
  final String paymentToken;

  /// Called when the payment is accepted (status: ACCEPTED).
  final PaymentCallback? onPaymentSuccess;

  /// Called when the payment is refused (status: REFUSED).
  final PaymentCallback? onPaymentFailed;

  /// Called when the payment is pending (status: PENDING, INITIATED, EXPIRED).
  final PaymentCallback? onPaymentPending;

  /// Called when the checkout is closed by the user or after payment completion.
  final CloseCallback? onClose;

  /// Called when a technical error occurs.
  final ErrorCallback? onError;
}
