import '../constants.dart';
import 'payment_error.dart';
import 'payment_response.dart';

/// Callback signature for payment result events.
typedef PaymentCallback = void Function(PaymentResponse data);

/// Callback signature for error events.
typedef ErrorCallback = void Function(PaymentError error);

/// Callback signature for the close event.
typedef CloseCallback = void Function();

/// Signature of a merchant-supplied payment status check.
///
/// The SDK calls this periodically while the checkout is open. Implement it by
/// querying **your own backend**, which in turn calls the CinetPay
/// `POST /v1/payment/check` endpoint. Return the raw JSON payload, or `null`
/// if the status could not be determined.
///
/// This is the only authoritative source of the payment result: the checkout
/// page itself may not report anything back to the app.
typedef PaymentStatusChecker = Future<Map<String, dynamic>?> Function();

/// Configuration for the CinetPay checkout flow.
///
/// The [paymentToken] is the only required parameter. It must be obtained
/// from your backend by calling the CinetPay API (`POST /v1/payment`) using
/// one of the server-side SDKs (cinetpay-js, cinetpay-python, cinetpay-go, etc.).
///
/// All callbacks are optional. Use them to react to payment events in your app.
class CheckoutConfig {
  /// Creates a [CheckoutConfig].
  ///
  /// The [paymentToken] must be a non-empty alphanumeric string (10-128 chars)
  /// obtained from your backend.
  const CheckoutConfig({
    required this.paymentToken,
    this.environment = CinetPayEnvironment.sandbox,
    this.checkoutBaseUrl,
    this.statusChecker,
    this.statusPollInterval = const Duration(seconds: 3),
    this.onPaymentSuccess,
    this.onPaymentFailed,
    this.onPaymentPending,
    this.onClose,
    this.onError,
  });

  /// The payment token obtained from your backend.
  ///
  /// This token is generated by calling the CinetPay API `POST /v1/payment`
  /// and is used to load the checkout page at
  /// `{secureBaseUrl}/checkout/{paymentToken}`.
  final String paymentToken;

  /// The CinetPay environment the [paymentToken] was created on.
  ///
  /// Defaults to [CinetPayEnvironment.sandbox], matching the JavaScript SDK.
  /// A token minted in production (`api.cinetpay.co`) will produce a `404` on
  /// the checkout page unless this is set to [CinetPayEnvironment.production].
  final CinetPayEnvironment environment;

  /// Overrides the checkout host entirely, ignoring [environment].
  ///
  /// Only needed when CinetPay provisions a dedicated host for you.
  final String? checkoutBaseUrl;

  /// Optional callback used to poll the authoritative payment status.
  ///
  /// See [PaymentStatusChecker]. Strongly recommended: without it, the SDK can
  /// only report the payment status detected from the checkout URL, with no
  /// amount or transaction id.
  final PaymentStatusChecker? statusChecker;

  /// How often [statusChecker] is invoked. Clamped to a minimum of 1 second.
  final Duration statusPollInterval;

  /// Called when the payment is accepted (status: ACCEPTED).
  final PaymentCallback? onPaymentSuccess;

  /// Called when the payment is refused (status: REFUSED).
  final PaymentCallback? onPaymentFailed;

  /// Called when the payment is pending (status: PENDING, INITIATED, EXPIRED).
  final PaymentCallback? onPaymentPending;

  /// Called when the checkout is closed by the user.
  ///
  /// Not called when the checkout closes after a payment result was dispatched.
  final CloseCallback? onClose;

  /// Called when a technical error occurs.
  final ErrorCallback? onError;
}
